# Generated by Django 5.2 on 2025-05-05 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Водитель',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('фио', models.CharField(max_length=100, verbose_name='ФИО водителя')),
                ('права', models.CharField(max_length=20, verbose_name='Номер водительского удостоверения')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Перевозчик',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100, verbose_name='Название компании')),
                ('контактное_лицо', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('телефон', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('транспортное_средство', models.CharField(max_length=100, verbose_name='Тип транспорта')),
                ('марка_автомобиля', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('гос_номер', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('водитель_фио', models.CharField(max_length=100, verbose_name='ФИО водителя')),
                ('водитель_удостоверение', models.CharField(max_length=50, verbose_name='Номер в/у')),
                ('лицензия_номер', models.CharField(max_length=50, verbose_name='Номер лицензии')),
                ('лицензия_срок', models.DateField(verbose_name='Срок действия лицензии')),
            ],
            options={
                'verbose_name': 'Перевозчик',
                'verbose_name_plural': 'Перевозчики',
                'ordering': ['название'],
            },
        ),
        migrations.CreateModel(
            name='Поставщик',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100, verbose_name='Название поставщика')),
                ('контактное_лицо', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('телефон', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('адрес', models.TextField(verbose_name='Юридический адрес')),
                ('условия_поставки', models.TextField(verbose_name='Условия поставки')),
                ('реквизиты', models.TextField(blank=True, null=True, verbose_name='Банковские реквизиты')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['название'],
            },
        ),
        migrations.CreateModel(
            name='ТранспортноеСредство',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('гос_номер', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('марка', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='ЗаявкаНаПоставку',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('номер', models.CharField(max_length=20, unique=True, verbose_name='Номер заявки')),
                ('дата_создания', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('клиент', models.CharField(max_length=100, verbose_name='Клиент')),
                ('плательщик', models.TextField(verbose_name='Плательщик')),
                ('адрес_отправки', models.TextField(verbose_name='Адрес отправки')),
                ('адрес_доставки', models.TextField(verbose_name='Адрес доставки')),
                ('товар', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('количество', models.PositiveIntegerField(verbose_name='Количество')),
                ('срок_поставки', models.DateField(verbose_name='Срок поставки')),
                ('статус', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('delivery', 'Доставляется'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('комментарий', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заявка на поставку',
                'verbose_name_plural': 'Заявки на поставку',
                'ordering': ['-дата_создания'],
                'indexes': [models.Index(fields=['номер'], name='supply_chai_номер_d2c4e5_idx'), models.Index(fields=['статус'], name='supply_chai_статус_0c1a0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Договор',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('номер', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('дата_заключения', models.DateField(verbose_name='Дата заключения')),
                ('условия_оплаты', models.TextField(verbose_name='Условия оплаты')),
                ('условия_поставки', models.TextField(verbose_name='Условия поставки')),
                ('срок_действия', models.DateField(verbose_name='Срок действия договора')),
                ('файл', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Скан договора')),
                ('заявка', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply_chain.заявканапоставку', verbose_name='Заявка на поставку')),
                ('поставщик', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply_chain.поставщик', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-дата_заключения'],
            },
        ),
        migrations.CreateModel(
            name='ТранспортнаяНакладная',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('номер', models.CharField(max_length=50, unique=True, verbose_name='Номер ТТН')),
                ('дата_составления', models.DateField(auto_now_add=True, verbose_name='Дата составления')),
                ('грузоотправитель', models.CharField(max_length=200, verbose_name='Грузоотправитель (наименование, адрес, телефон)')),
                ('грузополучатель', models.CharField(max_length=200, verbose_name='Грузополучатель (наименование, адрес, телефон)')),
                ('плательщик', models.CharField(max_length=200, verbose_name='Плательщик (наименование, адрес, реквизиты)')),
                ('код_продукции', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код продукции')),
                ('наименование', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование товара')),
                ('единица_измерения', models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица измерения')),
                ('вид_упаковки', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид упаковки')),
                ('количество_мест', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('масса_брутто', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Масса брутто, т')),
                ('масса_нетто', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Масса нетто, т')),
                ('цена', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена, руб.')),
                ('сумма', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма, руб.')),
                ('пункт_погрузки', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пункт погрузки (адрес, телефон)')),
                ('пункт_разгрузки', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пункт разгрузки (адрес, телефон)')),
                ('срок_доставки', models.DateField(blank=True, null=True, verbose_name='Срок доставки')),
                ('статус', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('canceled', 'Аннулирована')], default='draft', max_length=20, verbose_name='Статус накладной')),
                ('дата_отправки', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('дата_доставки', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('тип_груза', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип груза')),
                ('платежные_реквизиты', models.CharField(blank=True, max_length=200, null=True, verbose_name='Платежные реквизиты')),
                ('комментарий', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('водитель_фио', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.водитель', verbose_name='Водитель')),
                ('перевозчик', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.перевозчик')),
                ('транспортное_средство', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.транспортноесредство', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Транспортная накладная',
                'verbose_name_plural': 'Транспортные накладные',
                'ordering': ['-дата_составления'],
            },
        ),
        migrations.CreateModel(
            name='ОтчетОДоставке',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_прибытия', models.DateTimeField(verbose_name='Фактическая дата прибытия')),
                ('дата_убытия', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата убытия')),
                ('пробег', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег, км')),
                ('время_в_пути', models.DurationField(verbose_name='Общее время в пути')),
                ('средняя_скорость', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Средняя скорость, км/ч')),
                ('статус', models.CharField(choices=[('in_progress', 'В процессе доставки'), ('delivered', 'Доставлено'), ('partially', 'Доставлено частично'), ('canceled', 'Отменено'), ('problem', 'Проблема с доставкой')], default='in_progress', max_length=20, verbose_name='Статус доставки')),
                ('примечание', models.TextField(blank=True, null=True, verbose_name='Комментарий к доставке')),
                ('подтверждение_получателя', models.BooleanField(default=False, verbose_name='Подтверждение получения')),
                ('фото_документов', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/', verbose_name='Фото документов')),
                ('создано', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отчета')),
                ('обновлено', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('водитель', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.водитель', verbose_name='Водитель')),
                ('транспортная_накладная', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='отчеты_доставки', to='supply_chain.транспортнаянакладная', verbose_name='Транспортная накладная')),
                ('транспортное_средство', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.транспортноесредство', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Отчет о доставке',
                'verbose_name_plural': 'Отчеты о доставке',
                'ordering': ['-дата_прибытия'],
            },
        ),
        migrations.CreateModel(
            name='ФинансовыйОтчет',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('период_начала', models.DateField(verbose_name='Начало периода')),
                ('период_окончания', models.DateField(verbose_name='Окончание периода')),
                ('доходы', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма доходов')),
                ('расходы', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма расходов')),
                ('прибыль', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прибыль')),
                ('комментарий', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('файл', models.FileField(blank=True, null=True, upload_to='financial_reports/', verbose_name='Файл отчета')),
            ],
            options={
                'verbose_name': 'Финансовый отчет',
                'verbose_name_plural': 'Финансовые отчеты',
                'ordering': ['-период_начала'],
                'unique_together': {('период_начала', 'период_окончания')},
            },
        ),
        migrations.AddIndex(
            model_name='транспортнаянакладная',
            index=models.Index(fields=['номер'], name='supply_chai_номер_5eb6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='транспортнаянакладная',
            index=models.Index(fields=['дата_составления'], name='supply_chai_дата_со_9aab40_idx'),
        ),
        migrations.AddIndex(
            model_name='транспортнаянакладная',
            index=models.Index(fields=['статус'], name='supply_chai_статус_8304b6_idx'),
        ),
        migrations.AddIndex(
            model_name='отчетодоставке',
            index=models.Index(fields=['статус'], name='supply_chai_статус_710e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='отчетодоставке',
            index=models.Index(fields=['транспортная_накладная'], name='supply_chai_транспо_bb241b_idx'),
        ),
    ]
