# Generated by Django 5.2 on 2025-05-05 22:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='заявканапоставку',
            options={'ordering': ['-дата_создания', '-номер'], 'verbose_name': 'Заявка на поставку', 'verbose_name_plural': 'Заявки на поставку'},
        ),
        migrations.AddField(
            model_name='заявканапоставку',
            name='дата_изменения',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления заявки', verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='адрес_доставки',
            field=models.TextField(help_text='Полный адрес места доставки товара', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='адрес_отправки',
            field=models.TextField(help_text='Полный адрес места отправки товара', verbose_name='Адрес отправки'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='дата_создания',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата оформления заявки', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='клиент',
            field=models.CharField(help_text='Наименование клиента', max_length=100, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='количество',
            field=models.PositiveIntegerField(help_text='Количество товара в единицах измерения', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='комментарий',
            field=models.TextField(blank=True, help_text='Дополнительная информация по заявке', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='номер',
            field=models.PositiveIntegerField(help_text='Уникальный номер заявки', unique=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='плательщик',
            field=models.TextField(help_text='Реквизиты плательщика', verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='срок_поставки',
            field=models.DateField(help_text='Планируемая дата поставки', verbose_name='Срок поставки'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='статус',
            field=models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('delivery', 'Доставляется'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', help_text='Текущий статус заявки', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='заявканапоставку',
            name='товар',
            field=models.CharField(help_text='Наименование поставляемого товара', max_length=100, verbose_name='Наименование товара'),
        ),
        migrations.AddIndex(
            model_name='заявканапоставку',
            index=models.Index(fields=['дата_создания'], name='supply_chai_дата_со_e66d66_idx'),
        ),
        migrations.AddIndex(
            model_name='заявканапоставку',
            index=models.Index(fields=['срок_поставки'], name='supply_chai_срок_по_52f38b_idx'),
        ),
        migrations.AddConstraint(
            model_name='заявканапоставку',
            constraint=models.CheckConstraint(condition=models.Q(('срок_поставки__gte', models.F('дата_создания'))), name='check_delivery_date'),
        ),
    ]
