# Generated by Django 5.2 on 2025-05-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_alter_заявканапоставку_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='заявканапоставку',
            name='номер',
            field=models.PositiveIntegerField(blank=True, help_text='Уникальный номер заявки (генерируется автоматически)', null=True, unique=True, verbose_name='Номер заявки'),
        ),
    ]
