# Generated by Django 5.2 on 2025-05-05 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_alter_заявканапоставку_номер'),
    ]

    operations = [
        migrations.AlterField(
            model_name='договор',
            name='дата_заключения',
            field=models.DateField(default=datetime.date.today, help_text='Дата подписания договора', verbose_name='Дата заключения'),
        ),
    ]
