# Generated by Django 5.2 on 2025-05-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_alter_договор_дата_заключения'),
    ]

    operations = [
        migrations.AddField(
            model_name='транспортнаянакладная',
            name='автомобиль_гос_номер',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер автомобиля'),
        ),
        migrations.AddField(
            model_name='транспортнаянакладная',
            name='автомобиль_марка',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка автомобиля'),
        ),
    ]
