# Generated by Django 5.2 on 2025-05-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_транспортнаянакладная_автомобиль_гос_номер_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='транспортнаянакладная',
            name='перевозчик',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.перевозчик', verbose_name='Перевозчик'),
        ),
    ]
